### ISSUE TITLE
update docs with sink and duplex examples

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/muxrpc#27]
`//TODO: sink and duplex pull-streams` in the README is confusing, i thought it meant sink and duplex pull-streams were unsupported but after looking in the code i guess it just means there aren't examples. :sake:

**Comment by dominictarr** [comment]
hmm... that example is getting pretty cluttered. most of the time you use async and source.
sink is for uploads, and i don't think I have actually used duplex yet, outside of testing muxrpc.
maybe it would be better to have separate examples for that stuff?
