### ISSUE TITLE
api documentation!

### ISSUE THREAD

**Issue by dominictarr** [ssbc/muxrpc#34]
we don't have any );

**Comment by cryptix** [comment]
well.. i made [go-muxrpc](https://github.com/cryptix/go-muxprc) without any. Not meant as a palliation but encouragement. Having been through that valley myself, I can also try to proof read.

**Comment by kumavis** [comment]
please document `serializer` arg

**Comment by dominictarr** [comment]
@kumavis it defaults to https://github.com/dominictarr/packet-stream-codec
