### ISSUE TITLE
Way to return value and stream

### ISSUE THREAD

**Issue by jhiesey** [ssbc/muxrpc#38]
I'm changing an old, unfinished project of mine (https://github.com/jhiesey/webdht) from using `multiplex` and `rpc-stream` to this module.

There is one rpc call that previously returned a boolean, and then only opened a duplex stream if the boolean is true. Is there an elegant way to do that with this module? Essentially I'd like to return a duplex stream *and* have an async callback for other data.

Obviously I can pass the extra data over the stream but having a simple callback to would be useful. Or is there an easy way to do this I missed?

**Comment by dominictarr** [comment]
short answer: no.
long answer, you'd have to create two calls. maybe you'd do an async call and then pass a result of that to a stream. if you had a client thing that wrapped the muxrpc instance you could make this be a single call to the user. can you give a more concrete description of what this looks like, then I could advise you better.

**Comment by jhiesey** [comment]
For this particular case I can just detect if the stream gets any data before it ends (the callee end of the rpc can either decide to send data or end the stream immediately).

The wrapper approach is my backup plan. I'll reopen this if I have an example where that gets ugly.

**Comment by dominictarr** [comment]
👍
