### ISSUE TITLE
 TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by cryptix** [ssbc/muxrpc#43]
_sometimes_ sbot fails to connect and then crashes with this:

```
/home/cryptix/scuttle-shell/node_modules/muxrpc/stream.js:41
      args.push(function (err, value) {
           ^

TypeError: Cannot read property 'push' of undefined
    at Object.request (/home/cryptix/scuttle-shell/node_modules/muxrpc/stream.js:41:12)
    at PacketStream._onrequest (/home/cryptix/scuttle-shell/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/home/cryptix/scuttle-shell/node_modules/packet-stream/index.js:134:41)
    at /home/cryptix/scuttle-shell/node_modules/muxrpc/pull-weird.js:56:15
    at /home/cryptix/scuttle-shell/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/cryptix/scuttle-shell/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/cryptix/scuttle-shell/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/home/cryptix/scuttle-shell/node_modules/pull-reader/index.js:39:14)
    at more (/home/cryptix/scuttle-shell/node_modules/pull-reader/index.js:55:13)
    at /home/cryptix/scuttle-shell/node_modules/pull-reader/index.js:66:9
```

**Comment by dominictarr** [comment]
args is parsed from the json message sent in muxrpc connection `{name: [path], args:[...]}`
so if that happened... it some how got enough message to call `muxrpc/stream.request` but not enough to be a valid call! packet-stream-codec and packet-stream doesn't enforce that!... so you can crash any muxrpc server by sending a missing args, it seems. That part is easy to fix.

How exactly that happens is not so clear. do you have any more clues?
is it always stream.js on line 41? (if so, something is sending malformed `request` type, but not `stream`) how often?

if args is missing, seems like a chance that something else is missing too. I made a patch to fix that (in 6.4.2) should give you better idea what's going on anyway, and not crash - returns error to client instead.

**Comment by dominictarr** [comment]
one hunch: I've never seen this error, would bet a beer go is involved.

**Comment by cryptix** [comment]
> would bet a beer go is involved.

this could be true. We are currently trying to figure out a bug around to-soon-closing of streams but I would have thought EndErr is correctly handled on the js-side.. :cold_sweat: 

> do you have any more clues?

nope, sorry. Would have supplied if I had a solid producer... happens very infrequently.

**Comment by cryptix** [comment]
> do you have any more clues? - @dominictarr 

we just got this reproduced in our go-ssb integration tests. It happens when there is an additional EndErr packet on an async request. Granted, it's an error from the go side but it shouldn't crash the called party.

**Comment by dominictarr** [comment]
oh, any extra packets like that should definitely be ignored (and probably logged) or with an option to abort the entire connection (since then the peer will notice)

**Comment by cryptix** [comment]
is there a test case already where a server gets fed with a static list of packets instead of a client? than i can easily reproduce this.

**Comment by dominictarr** [comment]
if we don't have tests like that, we really should have tests like that. hmm, pretty sure I wrote tests like that for muxrpc@7, but 6 (which we reverted to) doesn't seem to have them.

**Comment by dominictarr** [comment]
(not sure if you could easily port them, easier to start from scratch)

**Comment by cryptix** [comment]
I tried to reproduce the bug but it seems like PSC's encode() can't construct them like go-muxrpc does. I'll try to put a tee-pipe into our interop tests to get the actual bytes sent next time I look into this.
