### ISSUE TITLE
Callback doesn't support third argument?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/muxrpc#47]
I understand that usually asynchronous functions pass two arguments, `err` and `val`, but I have a use for a third argument (https://github.com/flumedb/flumeview-hashtable/pull/3) that muxrpc seems to be removing. Is this intended behavior?

I've taken the example from the readme and added `thirdArgument` to illustrate the bug:

```javascript
var MRPC = require('muxrpc')
var pull = require('pull-stream')
var toPull = require('stream-to-pull-stream')
var net = require('net')

//we need a manifest of methods we wish to expose.
var manifest = {
  //async is a normal async function
  hello: 'async',

  //source is a pull-stream (readable)
  stuff: 'source'

  //TODO: sink and duplex pull-streams
}

//the actual methods which the server exposes
var api = {
  hello: function (name, cb) {
    cb(null, 'hello, ' + name + '!', 'thirdArgument')
  },
  stuff: function () {
    return pull.values([1, 2, 3, 4, 5])
  }
}

//pass the manifests into the constructor, and then pass the local api object you are wrapping
//(if there is a local api)
var client = MRPC(manifest, null) () //MRPC (remoteManifest, localManifest) (localApi)
var server = MRPC(null, manifest) (api)

net.createServer(function (stream) {
  stream = toPull.duplex(stream) //turn into a pull-stream
  //connect the output of the net stream to the muxrpc stream
  //and then output of the muxrpc stream to the net stream
  pull(stream, server.createStream(), stream)
}).listen(8080)
//connect a pair of duplex streams together.

var stream = toPull.duplex(net.connect(8080))
pull(stream, client.createStream(onClose), stream)

function onClose () {
  console.log('connected to muxrpc server')
}

//now you can call methods like this.

client.hello('world', function (err, value, thirdArgument) {
  if(err) throw err
  console.log(value, thirdArgument)
  // hello, world!
})

pull(client.stuff(), pull.drain(console.log))
```

## Expected output

```
hello, world! thirdArgument
1
2
3
4
5
```

## Actual output

```
hello, world! undefined
1
2
3
4
5
```
cc: @dominictarr

**Comment by cryptix** [comment]
Just as a workaround: Do you need the 3rd arg _really_? I mean, couldn’t you convert it to `opt = { first: .., third:..}`

Just thinking out loud and adding importance if that doesn’t work for legacy/preserving api compat.

**Comment by christianbundy** [comment]
If this wasn't an existing API then I could use an object instead, but I'd like to avoid breaking compatibility. When running the method locally it [works fine](https://github.com/flumedb/flumeview-hashtable/blob/8d2a9d58062b920e8e1071ce237e56e985db4b70/test/simple.js#L24), but when it's called over muxrpc it's limited to two arguments.

I've got a workaround for this specific need but I wanted to clarify whether the 2-arg limit is a bug or a design decision.

**Comment by ahdinosaur** [comment]
> clarify whether the 2-arg limit is a bug or a design decision.

i can't speak for @dominictarr, but personally i think 2-arg callbacks are a design decision, as they are a better abstraction for [the result type](https://en.wikipedia.org/wiki/Result_type).

> I'd like to avoid breaking compatibility

with regards to https://github.com/flumedb/flumeview-hashtable/pull/3, you should feel free to break compatibility! if the worry is adding `seq` to the returned `value` (which is a valid worry), then i thinking a breaking change with `{ value, seq }`, which is a clear upgrade path that only affects modules depending on `flumeview-hashtable`, is preferred to changing our expectation around callbacks to be able to return multiple values through additional arguments.

**Comment by dominictarr** [comment]
for muxrpc it's definitely a design decision. it's easy to map to cli and http etc. I think lets not add a second arg, and I'm generally moving apis exposed over muxrpc to only use a single arg when calling too (not counting the callback)

**Comment by christianbundy** [comment]
Sweet, I'll continue to use that pattern. Thank you!
