### ISSUE TITLE
Connection handshake

### ISSUE THREAD

**Issue by pfraze** [ssbc/muxrpc#5]
Long run, I think we're going to need to add a handshake to the rpc apis that establishes protocol and API compatibility, particularly RE: versions. This may not be part of muxrpc, but I thought it best to file the issue here.

It may make sense to implement this as an API call on top of muxrpc, eg `handshake()`. That would enable the APIs to define their own handshakes.

**Comment by dominictarr** [comment]
This ability was added by https://github.com/dominictarr/secret-handshake
