### ISSUE TITLE
What is `api.js` supposed to be?

### ISSUE THREAD

**Issue by staltz** [ssbc/muxrpc#51]
[In this commit](https://github.com/ssbc/muxrpc/commit/0c5b079c009c598002c576114f979a451cda1308), `api.js` was renamed to `remote-api.js`. Later, [in this commit](https://github.com/ssbc/muxrpc/commit/95b18e2d9d20af209e066f20324d02219546bdb3), `api.js` was re-added as a shortcut to `local-api.js`. Isn't the file `api.js` supposed to be a shortcut to `remote-api.js`?

**Comment by staltz** [comment]
bot no

**Comment by dominictarr** [comment]
ah yes that makes sense. I know I put the api.js back because something was using it directly... but now I'm not sure what used it.

**Comment by dominictarr** [comment]
ah okay I found it by removing api.js and trying to run tests with that muxrpc linked in. it's used by ssb-plugins, curiously it still works with _either_ `local-api` or `remote-api`... so the tests arn't very good.

this only effects out-of-process plugins, and given that no one has complained that they are broken I guess they arn't being used...
