### ISSUE TITLE
Should exported manifest included methods we don't have permission to run?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/muxrpc#55]
When running `manifest()` I'm seeing methods that aren't actually available to ssb-client, which gives me the impression that it's a permission thing (?). Is it correct that `api.manifest()` is returning methods I can't run?

**Comment by dominictarr** [comment]
yeah I think it just returns all the methods, then permissions don't get checked until you call the method.

**Comment by christianbundy** [comment]
Cool, thanks!
