### ISSUE TITLE
Criticisms of RPC

### ISSUE THREAD

**Issue by pfrazee** [ssbc/muxrpc#9]
Recently on IRC, we discussed an article in which Alan Kay explained OO. In his explanation, he derided RPC as a failed premise which OO solved. We were unsure what he meant specifically, so I [posed the question to Hacker News](https://news.ycombinator.com/item?id=8677865).

The most interesting response I got was this:

> That might be not what Alan Kay meant, but here's one description of fundamental problems with RPC: [1]
> 
> [...] the fundamental problem is that RPC tries to make a distributed invocation look like a local one. This can't work because the failure modes in distributed systems are quite different from those in local systems, so you find yourself having to introduce more and more infrastructure that tries to hide all the hard details and problems that lurk beneath. That's how we got Apollo NCS and Sun RPC and DCE and CORBA and DSOM and DCOM and EJB and SOAP and JAX-RPC, to name a few off the top of my head, each better than what came before in some ways but worse in other ways, especially footprint and complexity. But it's all for naught because no amount of infrastructure can ever hide those problems of distribution. Network partitions are real, timeouts are real, remote host and service crashes are real, the need for piecemeal system upgrade and handling version differences between systems is real, etc. [...]
> 
> [1] http://erlang.org/pipermail/erlang-questions/2008-May/035209.html

I recommend you read the actual email on the erlang list. (It's written by one of the architects at Basho.) He describes what a couple of the responses on HN described, which is that RPC tries to map the messaging onto a language, whereas messaging includes no strict definition. Why?

> Ultimately, RPC is a leaky abstraction. It can't hide what it tries to
> hide, and because of that, it can easily make the overall problem more
> difficult to deal with by adding a lot of accidental complexity.

I recommend you read the links in that email, especially "RPC Under Fire." Which of these criticisms apply to MuxRPC? How might this compare to go channels or erlang's messaging?

**Comment by dominictarr** [comment]
update: muxrpc now uses a length delimited encoding, which allows streams of buffers without having to encode them as base64.
